# Generated by Django 4.2.3 on 2023-07-07 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Factory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Sprocket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "outside_diameter",
                    models.IntegerField(help_text="Sprocket diameter."),
                ),
                (
                    "pitch_diameter",
                    models.IntegerField(
                        help_text="Pitch circle diameter of the sprocket."
                    ),
                ),
                (
                    "pitch",
                    models.IntegerField(
                        help_text="Distance between the centers of two adjacent pins."
                    ),
                ),
                (
                    "teeth",
                    models.IntegerField(help_text="Number of teeth the sprocket has."),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SprocketProduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actual",
                    models.IntegerField(help_text="Number of sprockets produced."),
                ),
                (
                    "goal",
                    models.IntegerField(help_text="Number of sprockets to produce."),
                ),
                (
                    "datetime_produced",
                    models.DateTimeField(
                        help_text="Date and time when sprockets were produced."
                    ),
                ),
                (
                    "factory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sprockets.factory",
                    ),
                ),
                (
                    "sprocket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sprockets.sprocket",
                    ),
                ),
            ],
        ),
    ]
